import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { auth } from "@/auth";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { SessionProvider } from "next-auth/react";
import Navbar from "@/components/site/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const session = await auth();
	return (
		<html lang="pt-BR">
			<body className={inter.className} suppressHydrationWarning>
				<SessionProvider session={session}>
					<ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
						<div className="flex min-h-screen w-full flex-col">
							<div className="sticky top-0 flex h-16 items-center gap-4 border-b bg-background/80 backdrop-blur-md px-4 md:px-6 z-50">
								<Navbar />
							</div>
							{children}
						</div>
					</ThemeProvider>
				</SessionProvider>
			</body>
		</html>
	);
}
