import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { auth } from "@/auth";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { SessionProvider } from "next-auth/react";
import Navbar from "@/components/site/navbar";
import { Providers } from "./providers";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const session = await auth();
	return (
		<html lang="pt-BR" suppressHydrationWarning>
			<body className={cn("min-h-screen bg-white antialiased", inter.className)}>
				<Providers>
					<SessionProvider session={session}>
						<Navbar />
						<div className="flex-1">{children}</div>
					</SessionProvider>
				</Providers>
			</body>
		</html>
	);
}
