import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { auth } from "@/auth";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { SessionProvider } from "next-auth/react";
import Navbar from "@/components/site/navbar";
import { Providers } from "./providers";
import { cn } from "@/lib/utils";
import dynamic from "next/dynamic";

// Carregar o componente de status de conexão apenas no cliente com SSR desabilitado
const ConnectionStatus = dynamic(() => import("@/app/components/ConnectionStatus"), { ssr: false });

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const session = await auth();
	return (
		<html lang="pt-BR" suppressHydrationWarning>
			<body className={cn("min-h-screen bg-white antialiased", inter.className)}>
				<Providers>
					<SessionProvider session={session}>
						<div className="sticky top-0 z-50 flex h-16 items-center gap-4 border-b bg-background/80 backdrop-blur-md px-4 md:px-6">
							<Navbar />
						</div>
						<div className="flex-1">{children}</div>
						<ConnectionStatus />
					</SessionProvider>
				</Providers>
			</body>
		</html>
	);
}
